spring:
  application:
    name: 01-Api
  boot:
    admin:
      client:
        url: http://localhost:2222/
    
#server:port: 1111
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
#Optional if port is 8761 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/