spring:
  application:
    name: application
   
  config:
    import: optional:configserver:http://localhost:8888
    
server:
  port: 9999
  
management:
  endpoints:
    web:
      exposure:
        include: refresh