spring:
  application:
    name: 02-Api
  boot:
    admin:
      client:
        url: "http://localhost:2222/"
        
server:
  port: 3333
  
  
management:
  endpoints:
    web:
      exposure:
        include: '*'  
  
  
 
#Optional if port is 8761 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
